/**
 * Beacon Suedtirol API
 * The API for the Beacon Suedtirol project for configuring beacons and accessing beacon data.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.bz.beacon.beaconsuedtirolsdk.swagger.client.model;

import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BeaconOrderData {
  
  @SerializedName("beaconId")
  private String beaconId = null;
  @SerializedName("instanceId")
  private String instanceId = null;
  @SerializedName("major")
  private Integer major = null;
  @SerializedName("minor")
  private Integer minor = null;
  @SerializedName("namespace")
  private String namespace = null;
  @SerializedName("uuid")
  private UUID uuid = null;
  @SerializedName("zoneCode")
  private String zoneCode = null;
  @SerializedName("zoneId")
  private Integer zoneId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBeaconId() {
    return beaconId;
  }
  public void setBeaconId(String beaconId) {
    this.beaconId = beaconId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInstanceId() {
    return instanceId;
  }
  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMajor() {
    return major;
  }
  public void setMajor(Integer major) {
    this.major = major;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMinor() {
    return minor;
  }
  public void setMinor(Integer minor) {
    this.minor = minor;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNamespace() {
    return namespace;
  }
  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getZoneCode() {
    return zoneCode;
  }
  public void setZoneCode(String zoneCode) {
    this.zoneCode = zoneCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getZoneId() {
    return zoneId;
  }
  public void setZoneId(Integer zoneId) {
    this.zoneId = zoneId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeaconOrderData beaconOrderData = (BeaconOrderData) o;
    return (this.beaconId == null ? beaconOrderData.beaconId == null : this.beaconId.equals(beaconOrderData.beaconId)) &&
        (this.instanceId == null ? beaconOrderData.instanceId == null : this.instanceId.equals(beaconOrderData.instanceId)) &&
        (this.major == null ? beaconOrderData.major == null : this.major.equals(beaconOrderData.major)) &&
        (this.minor == null ? beaconOrderData.minor == null : this.minor.equals(beaconOrderData.minor)) &&
        (this.namespace == null ? beaconOrderData.namespace == null : this.namespace.equals(beaconOrderData.namespace)) &&
        (this.uuid == null ? beaconOrderData.uuid == null : this.uuid.equals(beaconOrderData.uuid)) &&
        (this.zoneCode == null ? beaconOrderData.zoneCode == null : this.zoneCode.equals(beaconOrderData.zoneCode)) &&
        (this.zoneId == null ? beaconOrderData.zoneId == null : this.zoneId.equals(beaconOrderData.zoneId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.beaconId == null ? 0: this.beaconId.hashCode());
    result = 31 * result + (this.instanceId == null ? 0: this.instanceId.hashCode());
    result = 31 * result + (this.major == null ? 0: this.major.hashCode());
    result = 31 * result + (this.minor == null ? 0: this.minor.hashCode());
    result = 31 * result + (this.namespace == null ? 0: this.namespace.hashCode());
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.zoneCode == null ? 0: this.zoneCode.hashCode());
    result = 31 * result + (this.zoneId == null ? 0: this.zoneId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeaconOrderData {\n");
    
    sb.append("  beaconId: ").append(beaconId).append("\n");
    sb.append("  instanceId: ").append(instanceId).append("\n");
    sb.append("  major: ").append(major).append("\n");
    sb.append("  minor: ").append(minor).append("\n");
    sb.append("  namespace: ").append(namespace).append("\n");
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  zoneCode: ").append(zoneCode).append("\n");
    sb.append("  zoneId: ").append(zoneId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
