// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Beacon Suedtirol API
 * The API for the Beacon Suedtirol project for configuring beacons and accessing beacon data.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.bz.beacon.beaconsuedtirolsdk.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GroupApiKey {
  
  @SerializedName("apiKey")
  private String apiKey = null;
  @SerializedName("groupId")
  private Long groupId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getApiKey() {
    return apiKey;
  }
  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getGroupId() {
    return groupId;
  }
  public void setGroupId(Long groupId) {
    this.groupId = groupId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupApiKey groupApiKey = (GroupApiKey) o;
    return (this.apiKey == null ? groupApiKey.apiKey == null : this.apiKey.equals(groupApiKey.apiKey)) &&
        (this.groupId == null ? groupApiKey.groupId == null : this.groupId.equals(groupApiKey.groupId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.apiKey == null ? 0: this.apiKey.hashCode());
    result = 31 * result + (this.groupId == null ? 0: this.groupId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupApiKey {\n");
    
    sb.append("  apiKey: ").append(apiKey).append("\n");
    sb.append("  groupId: ").append(groupId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
