// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Beacon Suedtirol API
 * The API for the Beacon Suedtirol project for configuring beacons and accessing beacon data.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.bz.beacon.beaconsuedtirolsdk.swagger.client.model;

import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.InputStream;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.URI;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.URL;
import java.io.File;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Resource {
  
  @SerializedName("description")
  private String description = null;
  @SerializedName("file")
  private File file = null;
  @SerializedName("filename")
  private String filename = null;
  @SerializedName("inputStream")
  private InputStream inputStream = null;
  @SerializedName("open")
  private Boolean open = null;
  @SerializedName("readable")
  private Boolean readable = null;
  @SerializedName("uri")
  private URI uri = null;
  @SerializedName("url")
  private URL url = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public File getFile() {
    return file;
  }
  public void setFile(File file) {
    this.file = file;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFilename() {
    return filename;
  }
  public void setFilename(String filename) {
    this.filename = filename;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InputStream getInputStream() {
    return inputStream;
  }
  public void setInputStream(InputStream inputStream) {
    this.inputStream = inputStream;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getOpen() {
    return open;
  }
  public void setOpen(Boolean open) {
    this.open = open;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getReadable() {
    return readable;
  }
  public void setReadable(Boolean readable) {
    this.readable = readable;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public URI getUri() {
    return uri;
  }
  public void setUri(URI uri) {
    this.uri = uri;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public URL getUrl() {
    return url;
  }
  public void setUrl(URL url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return (this.description == null ? resource.description == null : this.description.equals(resource.description)) &&
        (this.file == null ? resource.file == null : this.file.equals(resource.file)) &&
        (this.filename == null ? resource.filename == null : this.filename.equals(resource.filename)) &&
        (this.inputStream == null ? resource.inputStream == null : this.inputStream.equals(resource.inputStream)) &&
        (this.open == null ? resource.open == null : this.open.equals(resource.open)) &&
        (this.readable == null ? resource.readable == null : this.readable.equals(resource.readable)) &&
        (this.uri == null ? resource.uri == null : this.uri.equals(resource.uri)) &&
        (this.url == null ? resource.url == null : this.url.equals(resource.url));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.file == null ? 0: this.file.hashCode());
    result = 31 * result + (this.filename == null ? 0: this.filename.hashCode());
    result = 31 * result + (this.inputStream == null ? 0: this.inputStream.hashCode());
    result = 31 * result + (this.open == null ? 0: this.open.hashCode());
    result = 31 * result + (this.readable == null ? 0: this.readable.hashCode());
    result = 31 * result + (this.uri == null ? 0: this.uri.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");
    
    sb.append("  description: ").append(description).append("\n");
    sb.append("  file: ").append(file).append("\n");
    sb.append("  filename: ").append(filename).append("\n");
    sb.append("  inputStream: ").append(inputStream).append("\n");
    sb.append("  open: ").append(open).append("\n");
    sb.append("  readable: ").append(readable).append("\n");
    sb.append("  uri: ").append(uri).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
