// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Beacon Suedtirol API
 * The API for the Beacon Suedtirol project for configuring beacons and accessing beacon data.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.bz.beacon.beaconsuedtirolsdk.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class URL {
  
  @SerializedName("authority")
  private String authority = null;
  @SerializedName("content")
  private Object content = null;
  @SerializedName("defaultPort")
  private Integer defaultPort = null;
  @SerializedName("file")
  private String file = null;
  @SerializedName("host")
  private String host = null;
  @SerializedName("path")
  private String path = null;
  @SerializedName("port")
  private Integer port = null;
  @SerializedName("protocol")
  private String protocol = null;
  @SerializedName("query")
  private String query = null;
  @SerializedName("ref")
  private String ref = null;
  @SerializedName("userInfo")
  private String userInfo = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthority() {
    return authority;
  }
  public void setAuthority(String authority) {
    this.authority = authority;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getContent() {
    return content;
  }
  public void setContent(Object content) {
    this.content = content;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDefaultPort() {
    return defaultPort;
  }
  public void setDefaultPort(Integer defaultPort) {
    this.defaultPort = defaultPort;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFile() {
    return file;
  }
  public void setFile(String file) {
    this.file = file;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHost() {
    return host;
  }
  public void setHost(String host) {
    this.host = host;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPath() {
    return path;
  }
  public void setPath(String path) {
    this.path = path;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPort() {
    return port;
  }
  public void setPort(Integer port) {
    this.port = port;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProtocol() {
    return protocol;
  }
  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getQuery() {
    return query;
  }
  public void setQuery(String query) {
    this.query = query;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRef() {
    return ref;
  }
  public void setRef(String ref) {
    this.ref = ref;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserInfo() {
    return userInfo;
  }
  public void setUserInfo(String userInfo) {
    this.userInfo = userInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    URL URL = (URL) o;
    return (this.authority == null ? URL.authority == null : this.authority.equals(URL.authority)) &&
        (this.content == null ? URL.content == null : this.content.equals(URL.content)) &&
        (this.defaultPort == null ? URL.defaultPort == null : this.defaultPort.equals(URL.defaultPort)) &&
        (this.file == null ? URL.file == null : this.file.equals(URL.file)) &&
        (this.host == null ? URL.host == null : this.host.equals(URL.host)) &&
        (this.path == null ? URL.path == null : this.path.equals(URL.path)) &&
        (this.port == null ? URL.port == null : this.port.equals(URL.port)) &&
        (this.protocol == null ? URL.protocol == null : this.protocol.equals(URL.protocol)) &&
        (this.query == null ? URL.query == null : this.query.equals(URL.query)) &&
        (this.ref == null ? URL.ref == null : this.ref.equals(URL.ref)) &&
        (this.userInfo == null ? URL.userInfo == null : this.userInfo.equals(URL.userInfo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.authority == null ? 0: this.authority.hashCode());
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    result = 31 * result + (this.defaultPort == null ? 0: this.defaultPort.hashCode());
    result = 31 * result + (this.file == null ? 0: this.file.hashCode());
    result = 31 * result + (this.host == null ? 0: this.host.hashCode());
    result = 31 * result + (this.path == null ? 0: this.path.hashCode());
    result = 31 * result + (this.port == null ? 0: this.port.hashCode());
    result = 31 * result + (this.protocol == null ? 0: this.protocol.hashCode());
    result = 31 * result + (this.query == null ? 0: this.query.hashCode());
    result = 31 * result + (this.ref == null ? 0: this.ref.hashCode());
    result = 31 * result + (this.userInfo == null ? 0: this.userInfo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class URL {\n");
    
    sb.append("  authority: ").append(authority).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("  defaultPort: ").append(defaultPort).append("\n");
    sb.append("  file: ").append(file).append("\n");
    sb.append("  host: ").append(host).append("\n");
    sb.append("  path: ").append(path).append("\n");
    sb.append("  port: ").append(port).append("\n");
    sb.append("  protocol: ").append(protocol).append("\n");
    sb.append("  query: ").append(query).append("\n");
    sb.append("  ref: ").append(ref).append("\n");
    sb.append("  userInfo: ").append(userInfo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
