default_platform(:android)

platform :android do
  desc "Test the package"
  lane :test do
    gradle(task: "clean")

    gradle(task: "test")

    gradle(
      task: ":beaconsuedtirolsdk:assemble",
      build_type: "Release"
    )
  end

  desc "Release the package"
  lane :release do
    android_set_version_name(
      version_name: ENV["TAG"],
      gradle_file: "beaconsuedtirolsdk/build.gradle"
    )

    gradle(task: "clean")

    gradle(task: "test")

    gradle(
      task: ":beaconsuedtirolsdk:assemble",
      build_type: "Release"
    )

    gradle(
      task: ":beaconsuedtirolsdk:publish"
    )
  end

  desc "Snapshot release of the package"
  lane :appSnapshot do
    android_set_version_name(
      version_name: ENV["TAG"],
      gradle_file: "beaconsuedtirolsdk/build.gradle"
    )

    gradle(task: "clean")

    gradle(task: "test")

    gradle(
      task: ":beaconsuedtirolsdk:assemble",
      build_type: "Snapshot"
    )

    gradle(
      task: ":beaconsuedtirolsdk:publish"
    )
  end
end
