/*
 * Beacon Suedtirol API
 * The API for the Beacon Suedtirol project for configuring beacons and accessing beacon data.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.bz.beacon.beaconsuedtirolsdk.swagger.client.api;

import it.bz.beacon.beaconsuedtirolsdk.swagger.client.ApiException;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.AuthenticationRequest;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.AuthenticationToken;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.AuthenticationTokenCheck;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.AuthenticationTokenCheckRequest;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.BaseMessage;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.ResetPasswordChange;
import it.bz.beacon.beaconsuedtirolsdk.swagger.client.model.ResetPasswordRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthControllerApi
 */
@Ignore
public class AuthControllerApiTest {

    private final AuthControllerApi api = new AuthControllerApi();

    
    /**
     * Check whether a token is valid or not
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkTokenUsingPOSTTest() throws ApiException {
        AuthenticationTokenCheckRequest request = null;
        AuthenticationTokenCheck response = api.checkTokenUsingPOST(request);

        // TODO: test validations
    }
    
    /**
     * Check whether a token is valid or not
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resetPasswordChangeUsingPOSTTest() throws ApiException {
        ResetPasswordChange resetPasswordChange = null;
        BaseMessage response = api.resetPasswordChangeUsingPOST(resetPasswordChange);

        // TODO: test validations
    }
    
    /**
     * Check whether a token is valid or not
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resetPasswordRequestUsingPOSTTest() throws ApiException {
        ResetPasswordRequest resetPasswordRequest = null;
        BaseMessage response = api.resetPasswordRequestUsingPOST(resetPasswordRequest);

        // TODO: test validations
    }
    
    /**
     * signin
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signinUsingPOSTTest() throws ApiException {
        AuthenticationRequest data = null;
        AuthenticationToken response = api.signinUsingPOST(data);

        // TODO: test validations
    }
    
}
